### ISSUE TITLE
item found but won't delete from the database

### ISSUE THREAD

**Issue by RettBehrens** [RettBehrens/project-2-there-again#7]
// this is the delete functionality
app.delete('/deleteRoute', function business_delete(req, res) {
	console.log('delete route reached');
	console.log(req.user);
	console.log(req.body.id);
	db.User.findOne({_id: req.user._id}, function(err,user) {
		if(err) {
			console.log(err);
		} else if (user) {
			console.log(user);
			db.Business.findOneAndRemove({_id: req.body.id}, function(err, deleted) {
				if(err) {
					console.log(err);
				} else {
					res.json(deleted);
				}
			});
		}
	});
});

**Comment by RettBehrens** [comment]
the code above gets close but does not successfully delete the listing from the user list

**Comment by stefems** [comment]
Can you add three of these ` to the top and bottom of your code sample so that it is formatted?

**Comment by RettBehrens** [comment]
```
// this is the delete functionality
app.delete('/deleteRoute', function business_delete(req, res) {
	console.log('delete route reached');
	console.log(req.user);
	console.log(req.body.id);
	db.User.findOne({_id: req.user._id}, function(err,user) {
		if(err) {
			console.log(err);
		} else if (user) {
			console.log(user);
			db.Business.findOneAndRemove({_id: req.body.id}, function(err, deleted) {
				if(err) {
					console.log(err);
				} else {
					res.json(deleted);
				}
			});
		}
	});
});
```

**Comment by stefems** [comment]
Does removing a document from a collection change the user document that exists in a different collection?

**Comment by RettBehrens** [comment]
var userId defined 598d200992ebe6b3aa4be55d
var businessToDeleteId defined 598d202292ebe6b3aa4be55e

How do I tell mongo to find (businessToDeleteId) within (userId) and delete it..?
